name: Django Firebase CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version used in your Django project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add commands to run your Django tests here

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@v1
      with:
        args: deploy --token "${{ secrets.firebasetoken}}" --only hosting  # Replace FIREBASE_TOKEN with your Firebase token secret
